### ISSUE TITLE
Move contract to contracts repo

### ISSUE THREAD

**Issue by Rizato** [polyswarm/worker-registry#11] opened 2018-11-02 22:01 UTC
**Is your feature request related to a problem? Please describe.**
Worker registry contracts should be in contracts so it can be deployed to geth & added to consul

**Comment by myhndl** [comment] 2018-11-05 07:22
this is a dupe of: https://github.com/polyswarm/contracts/issues/68

**Closed as completed by myhndl** 2018-11-05 07:22 UTC
